### ISSUE TITLE
"Error: Cannot find module" when using with webpack 2.1.0-beta.25

### ISSUE THREAD

**Issue by baonhan** [webpack/grunt-webpack#90]
Sample code: http://plnkr.co/edit/Xl8vvvnN0qNO1PC5hDFG?p=info

Webpack can run by `npm run webpack` but failed with the following error when running `grunt webpack`:

```
ERROR in ./main.ts
Module build failed: Error: Cannot find module './node_modules/awesome-typescript-loader/dist/entry.js'
  at Function.Module._resolveFilename (module.js:469:15)
  at Function.Module._load (module.js:417:25)
  at Module.require (module.js:497:17)
  at require (internal/module.js:20:19)
  at loadLoader (W:\ssp\testwebpack\node_modules\loader-runner\lib\loadLoader.js:13:17)
  at iteratePitchingLoaders (W:\ssp\testwebpack\node_modules\loader-runner\lib\LoaderRunner.js:164:2)
  at runLoaders (W:\ssp\testwebpack\node_modules\loader-runner\lib\LoaderRunner.js:357:2)
  at NormalModule.doBuild (W:\ssp\testwebpack\node_modules\webpack\lib\NormalModule.js:131:2)
  at NormalModule.build (W:\ssp\testwebpack\node_modules\webpack\lib\NormalModule.js:179:15)
  at Compilation.buildModule (W:\ssp\testwebpack\node_modules\webpack\lib\Compilation.js:127:9)
  at Compilation.<anonymous> (W:\ssp\testwebpack\node_modules\webpack\lib\Compilation.js:404:8)
  at W:\ssp\testwebpack\node_modules\webpack\lib\NormalModuleFactory.js:74:13
  at NormalModuleFactory.applyPluginsAsyncWaterfall (W:\ssp\testwebpack\node_modules\tapable\lib\Tapable.js:123:70)
  at onDoneResolving (W:\ssp\testwebpack\node_modules\webpack\lib\NormalModuleFactory.js:49:11)
  at onDoneResolving (W:\ssp\testwebpack\node_modules\webpack\lib\NormalModuleFactory.js:165:6)
  at W:\ssp\testwebpack\node_modules\webpack\lib\NormalModuleFactory.js:161:6
```

| software         | version|
| ---------------- | -------|
| webpack          |  2.1.0-beta.25 |
| grunt-webpack    | 2.0.0-beta.1 |
| grunt            |  1.0.1 |
| node             | 6.9.1 |
| npm              | 3.9.0 |
| Operating System | Windows 7 |

**Comment by danez** [comment]
thanks for reporting, this should be fixed in `2.0.0-beta.2`. Can you check if it works for you now?
